server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IPR1
    username: postgres
    password: postgre
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  logging:
    level:
      root: INFO
      com.example: DEBUG
    file:
      name: logs/application.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    enable:
      http: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true